CREATE TABLESPACE CONCSV
 LOGGING
  DATAFILE 'CONCSV.ORA'
SIZE 128M REUSE  AUTOEXTEND  ON NEXT  1024K MAXSIZE  128M
DEFAULT  STORAGE ( INITIAL 40K NEXT 40K MINEXTENTS 1 MAXEXTENTS  2147483645 PCTINCREASE 50 );

CREATE USER concsv identified by concsv default tablespace CONCSV TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM, drop public synonym, UNLIMITED TABLESPACE TO CONCSV;