GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_DIM TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_TEMPS TO WWW_HELIUM;
GRANT SELECT, UPDATE, INSERT, DELETE ON HEL_EXPLOT_FET TO WWW_HELIUM;
