-- ConCSV 2.2.1: índexs de les taules del backoffice (claus foranes i camps de consulta).

CREATE INDEX CSV_AVIS_ENTITAT_FK_I ON CSV_AVIS (ENTITAT_ID);
CREATE INDEX CSV_AVIS_DATA_INICI_I ON CSV_AVIS (DATA_INICI);
CREATE INDEX CSV_AVIS_DATA_FINAL_I ON CSV_AVIS (DATA_FINAL);
