-- ConCSV 2.2.1: claus primàries, úniques, foranes i restriccions de les taules del backoffice.

ALTER TABLE CSV_ENTITAT ADD (
  CONSTRAINT CSV_ENTITAT_PK PRIMARY KEY (ID),
  CONSTRAINT CSV_ENTITAT_CODI_UK UNIQUE (CODI),
  CONSTRAINT CSV_ENTITAT_DIR3_UK UNIQUE (CODI_DIR3));

ALTER TABLE CSV_USUARI ADD (
  CONSTRAINT CSV_USUARI_PK PRIMARY KEY (CODI));

ALTER TABLE CSV_AVIS ADD (
  CONSTRAINT CSV_AVIS_PK PRIMARY KEY (ID));

ALTER TABLE CSV_AVIS ADD CONSTRAINT CSV_AVIS_ENTITAT_FK
  FOREIGN KEY (ENTITAT_ID) REFERENCES CSV_ENTITAT (ID);
