#8 Afegir una caché de documents a FileSystem

# Propietats afegides al concsv.system.properties:

# Path al directori dels fitxers de ConCSV
es.caib.concsv.fitxers=/app/concsv

# Propietats afegides al concsv.properties:

es.caib.concsv.cache.activa=true
es.caib.concsv.cache.ttl.minuts=30

