# #################################
# PROPIETATS AFEGIDES
# #################################

# Path al directori dels fitxers de ConCSV
es.caib.concsv.fitxers=/app/concsv

# Activació de la caché de documents
es.caib.concsv.cache.activa=true
# Temps en minuts que es mantindrà un document en caché des del darrer accés abans de que s'esborri automàticament del directori de la caché
es.caib.concsv.cache.ttl.minuts=30


# #################################
# PROPIETATS ESBORRADES
# #################################

es.caib.concsv.do.tiny
es.caib.concsv.tiny.rest.url
es.caib.concsv.tiny.username
es.caib.concsv.tiny.password