#91 Implementar consulta de logs desde comanda 

# Path del directori on es troben els logs de l'aplicació per poder-los consultar per Comanda
es.caib.concsv.logs.location=/app/jboss-eap-7.2/standalone/log