# ConCSV 2.1.0. 

# #58 Desenvolupament del nou frontend utilitzant React

# PROPIETATS AFEGIDES

# URL de l'API pel front amb React
es.caib.concsv.front.api.url=https://dev.caib.es/concsvfront/api
# Propietats pel captcha
es.caib.concsv.front.recaptcha.enabled=false
es.caib.concsv.front.recaptcha.sitekey=6Lfjx_8nAAAAANO0Mqpuoj6lowM4PiEyho0aFkdY


# Ruta al fitxer de text opcional amb la llista de codis CSV's exclosos per descarregar l'original
es.caib.concsv.arxiu.documents.exclosos.path=/opt/webapps/concsv/documents-exclosos.txt

# Indica si amagar per defecte el botó de descàrrega del botó original per documents amb versió imprimible.
es.caib.concsv.amagar.boto.original=true
